# App engine app.yaml configuration File documentation:
# https://cloud.google.com/appengine/docs/standard/python3/config/appref 

#TODO: specify runtime. THis is a key value pair. The key is `runtime` and the
# value is `python27` (for Python 2.7)
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: MAP/index.html
  upload: MAP/index.html

- url: /(.*)
  static_files: MAP/\1
  upload: MAP/(.*)